# Choose the Image which has Node installed already
FROM mhart/alpine-node:14

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY . .

EXPOSE $PORT
EXPOSE 80
CMD [ "node", "serve-frontend-proxy.js" ]