# docker-compose file managing Nginx and the application
# Loading some variables from the .env file:
#   - DOMAIN: DNS domain name
#   - EMAIL: Maintainer email
#   - APP_FOLDER: Directory containing the application
#   - FLASK_APP: Flask entrypoint
#   - FLASK_ENV: Flask environment

version: "3.2"

services:
  nginx:
    image: normalone7/erik-web-app-api-nginx:latest
    build:
      context: ./nginx
      args:
        DOMAIN: ${DOMAIN}
        EMAIL: ${EMAIL}
        FLASK: application
    ports:
      - 5007:5007
      - 5006:5006
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - application

  application:
    image: normalone7/erik-web-app-api-app:latest
    build: ./${APP_FOLDER}
    command: gunicorn --bind 0.0.0.0:5005 --workers 3 ${FLASK_APP}:app
    environment:
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 5005:5005
