#Build docker image for backend and push to Heroku
#Formerly used snithyanantham/docker-compose-multiple-apps-heroku-deploy base action
name: Deploy Vue and Frontend Proxy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Vue and Frontend Proxy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # base action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "erik-web-app"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
