#Build docker image for backend and push to Heroku
name: "Backend Docker and Heroku Build"
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Docker-Compose and Push to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          docker_compose_file: "./api-server/docker-compose.yml"
          heroku_apps: '[{"imagename":"api-server_application","appname":"erik-web-app-api","apptype":"web"},{"imagename":"api-server_nginx","appname":"erik-web-app-api-ngnix","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type
