name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up node 
      uses: actions/setup-node@v1
    - name: Install Deps
      run: npm install
    - name: Unit Tests 
      run: npm run ci-test
